sqlloc.release_directory: /opt/sap
sqlloc.server_name: SYBASE
sqlloc.sa_login: sa
sqlloc.sa_password: Sybase123
sqlloc.default_language: us_english
sqlloc.default_characterset: utf8
sqlloc.sort_order: altdict
sqlloc.language_install_list: us_english
sqlloc.language_remove_list: USE_DEFAULT
sqlloc.characterset_install_list: utf8,iso15,roman9
sqlloc.characterset_remove_list: USE_DEFAULT
