srvbuild.release_directory: USE_DEFAULT
srvbuild.product: sqlsrv
srvbuild.server_name: SYBASE
srvbuild.sa_password: Sybase123
srvbuild.new_config: yes
srvbuild.do_add_server: yes
srvbuild.do_upgrade: no
srvbuild.network_protocol_list: tcp
srvbuild.network_hostname_list: localhost
srvbuild.network_port_list: 5000
srvbuild.application_type: USE_DEFAULT
srvbuild.server_page_size: USE_DEFAULT
srvbuild.master_device_physical_name: /opt/sap/data/master.dat
srvbuild.master_device_size: 150
srvbuild.master_database_size: 100
srvbuild.errorlog: USE_DEFAULT
srvbuild.sybsystemprocs_device_physical_name: /opt/sap/data/sysprocs.dat
srvbuild.sybsystemprocs_device_size: USE_DEFAULT
srvbuild.sybsystemprocs_database_size: USE_DEFAULT
srvbuild.sybsystemdb_device_physical_name: /opt/sap/data/sybsysdb.dat
srvbuild.sybsystemdb_device_size: USE_DEFAULT
srvbuild.sybsystemdb_database_size: USE_DEFAULT
srvbuild.tempdb_device_physical_name: /opt/sap/data/tempdbdev.dat
srvbuild.tempdb_device_size: 250
srvbuild.tempdb_database_size: 250
#srvbuild.default_backup_server: SYBASE_BS
#srvbuild.addl_cmdline_parameters: 
srvbuild.shmem: /opt/sap/ASE-16_0
srvbuild.do_configure_pci: no
#srvbuild.sybpcidb_device_physical_name: /opt/sap/data/sybpcidbdev_data.dat
srvbuild.sybpcidb_device_size: USE_DEFAULT
srvbuild.sybpcidb_database_size: USE_DEFAULT
srvbuild.do_optimize_config: no
srvbuild.avail_physical_memory: USE_DEFAULT
srvbuild.avail_cpu_num: USE_DEFAULT
srvbuild.configure_remote_command_and_control_agent_ase: USE_DEFAULT
srvbuild.enable_ase_for_ase_cockpit_monitor: no
#srvbuild.technical_user: tech_user
#srvbuild.technical_user_password: ********
srvbuild.addl_build_parameters: 
