services:
  database:
    build: ../
    environment:
      - DATABASE=TESTDB
      - SA_PASSWORD=Sybase1234
    entrypoint: entrypoint.sh
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./init/:/docker-entrypoint-initdb.d/:ro
      - logs:/log/
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s

  test:
    image: alpine:3.16
    working_dir: /scripts 
    command: ./test.sh
    volumes:
      - ./test:/scripts:ro
      - logs:/log/:ro
    depends_on:
      database:
        condition: service_healthy

volumes:
  logs:
    