services:
  database:
    build: ../
    environment:
      - DATABASE=TESTDB
      - SA_PASSWORD=Sybase1234
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./init/:/docker-entrypoint-initdb.d/:ro
      - logs:/log/

  test:
    image: alpine:3.16
    command: /test.sh
    volumes:
      - ./test.sh:/test.sh:ro
      - ./wait-for-file.sh:/wait-for-file.sh:ro
      - logs:/log/:ro
    depends_on:
      - database

volumes:
  logs:
    