services:
  database:
    build: ../
    environment:
      - DATABASE=TESTDB
      - SA_PASSWORD=Sybase1234
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  test:
    image: alpine:3.16
    command: sleep 60 && echo test done
    depends_on:
      - database
    