name: Test
on:
  pull_request:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build images
      run: docker compose build
    
    - name: Run test
      run: docker compose run test

    - name: Run database create assertion
      run: docker compose logs | grep "Database 'TESTDB' is now online"
    
    - name: Run database 1-table.sql init file assertion
      run: docker compose logs | grep "running /docker-entrypoint-initdb.d/1-table.sql"

    - name: Run database 2-data.sql.gz init file assertion
      run: docker compose logs | grep "running /docker-entrypoint-initdb.d/2-data.sql.gz"
    
    - name: Run database should_be_ignored.txt ignored file assertion
      run: docker compose logs | grep "ignoring /docker-entrypoint-initdb.d/should_be_ignored.txt"
     
    - name: Run Select assertions
      run: | 
        docker compose logs | grep "IDROW                 TEST_FIELD1" && \
        docker compose logs | grep "--------------------- -----------" && \
        docker compose logs | grep "                    1 1"
